services:
  next:
    build:
      context: .
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXT_PUBLIC_AUTH_SERVER_URL: "http://localhost:4000"
      NEXT_PUBLIC_RESOURCE_SERVER_URL: "http://localhost:5000"
      AUTH_SERVER_URL: "http://localhost:4000"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.next
      - /usr/src/app/node_modules
    depends_on:
      - auth-server
      - resource-server

  auth-server:
    build:
      context: ../auth-server/app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      PORT: 4000
      CORS_ORIGIN: http://localhost:3000
      JWKS_URL: http://localhost:4000/.well-known/jwks.json
      AUDIENCE: nextjs_client
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      ISSUER: http://localhost:4000
    ports:
      - 4000:4000
    volumes:
      - ../auth-server/app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  resource-server:
    build:
      context: ../resource-server/app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      PORT: 5000
      RESOURCE_SERVER_URL: http://localhost:5000
      AUTH_SERVER_URL: http://localhost:4000
      ISSUER: http://localhost:4000
      JWKS_URL: http://localhost:4000/.well-known/jwks.json
      AUDIENCE: nextjs_client
    ports:
      - 5000:5000
    volumes:
      - ../resource-server/app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - auth-server

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
